- name: Simple playbook
  hosts: all
  tasks:
    - name: List Jobs from Automation Controller
      ansible.controller.job_list:
        status: successful
      register: joblist
    - name: Debug joblist
      ansible.builtin.debug:
        var: joblist
